### ISSUE TITLE
Find all instances of form_for.error_messages and fix

### ISSUE THREAD

**Issue by ascendantlogic** [Cleveland2030Club/2030Club#25]
NoMethodError in Users#edit

Showing /Users/mattcase/2030Club/app/views/users/edit.html.erb where line #6 raised:

undefined method `error_messages' for #ActionView::Helpers::FormBuilder:0x007fd6c4a390b0
Extracted source (around line #6):

5:    <% form_for @user do |f| %>
6:        <%= f.error_messages %>

**Comment by ascendantlogic** [comment]
These error messages need to be appropriately styled still

**Comment by CoffeeAndCode** [comment]
closing for new issue after fixing remaining instances of `error_messages` calls.  new issue #37 handles styling.
