### ISSUE TITLE
Clicking "Become a Member" results in a stack trace

### ISSUE THREAD

**Issue by ascendantlogic** [Cleveland2030Club/2030Club#3]
NoMethodError in Registrations#new

Showing /Users/mattcase/2030Club/app/views/registrations/new.html.erb where line #4 raised:

undefined method `error_messages' for #ActionView::Helpers::FormBuilder:0x007fbab38a9d08
Extracted source (around line #4):

 3:   <% form_for @registration, :url => registration_path do |f| %>
 4:   <%= f.error_messages %>

**Comment by ascendantlogic** [comment]
form.error_messages was removed in Rails 3.x. I have it displaying error messages on registration failure but they are not styled properly.

**Comment by ascendantlogic** [comment]
Accidentally checked the fix in for this under this commit: 

https://github.com/Cleveland2030Club/2030Club/commit/bad5067fd54c2d0eb14780d79029ad84eb4f163e

**Comment by CoffeeAndCode** [comment]
Issue #3 fixed in previous commit.
