### ISSUE TITLE
Move js/css/images from public to assets

### ISSUE THREAD

**Issue by ascendantlogic** [Cleveland2030Club/2030Club#7]
Rails 3 introduced the asset pipeline which turned javascript, CSS and images into first class citizens. We are seeing a lot of display issues because the files still reside in the public folder. Move these into the app/assets folder and ensure that they play nicely with the new pipeline.

**Comment by CoffeeAndCode** [comment]
Completed by @kmsolorio in the `rails3_upgrade` branch.  Anything that was missed can be picked up in separate issues.
